name: Action Variables
run-name: Show Action Variables

env:
  WORKFLOW_VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: not use environment
        run: | 
          echo vars.VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}
          echo env.VARIABLE_SCOPE: ${{ env.VARIABLE_SCOPE }}
          echo env.WORKFLOW_VARIABLE_SCOPE: ${{ env.WORKFLOW_VARIABLE_SCOPE }}

  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: use environment(prod)
        run: | 
          echo vars.VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}
          echo env.VARIABLE_SCOPE: ${{ env.VARIABLE_SCOPE }}
          echo env.WORKFLOW_VARIABLE_SCOPE: ${{ env.WORKFLOW_VARIABLE_SCOPE }}

  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: use environment(dev)
        run: | 
          echo vars.VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}
          echo env.VARIABLE_SCOPE: ${{ env.VARIABLE_SCOPE }}
          echo env.WORKFLOW_VARIABLE_SCOPE: ${{ env.WORKFLOW_VARIABLE_SCOPE }}

  unknown:
    runs-on: ubuntu-latest
    environment: unknown
    steps:
      - name: use environment(unknown)
        run: | 
          echo vars.VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}
          echo env.VARIABLE_SCOPE: ${{ env.VARIABLE_SCOPE }}
          echo env.WORKFLOW_VARIABLE_SCOPE: ${{ env.WORKFLOW_VARIABLE_SCOPE }}
