name: Action Variables
run-name: Show Action Variables

env:
  VARIABLE_SCOPE: ${{ vars.VARIABLE_SCOPE }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: env
        run: | 
          echo ${{ env.VARIABLE_SCOPE }}
      - name: vars
        run: | 
          echo ${{ vars.VARIABLE_SCOPE }}

  variables2:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: env
        run: | 
          echo ${{ env.VARIABLE_SCOPE }}
      - name: vars
        run: | 
          echo ${{ vars.VARIABLE_SCOPE }}
