name: Concurrency Workflow
run-name: Concurrency

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#concurrency: concurrency-group

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1
        run: | 
          for i in {1..10000000}
            do
            echo "Welcome $i times" > /dev/null
          done
          echo "job1 completed"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2
        run: | 
          for i in {1..10000000}
            do
            echo "Welcome $i times" > /dev/null
          done
          echo "job2 completed"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job3
        run: | 
          for i in {1..10000000}
            do
            echo "Welcome $i times" > /dev/null
          done
          echo "job3 completed"
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Job4
        run: | 
          for i in {1..10000000}
            do
            echo "Welcome $i times" > /dev/null
          done
          echo "job4 completed"
  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Job5
        run: | 
          for i in {1..10000000}
            do
            echo "Welcome $i times" > /dev/null
          done
          echo "job5 completed"
