name: JSON Matrix Workflow
run-name: JSON Matrix

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set matrix
        id: set-matrix
        run: |
          ls
          pwd
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
          matrix=$(jq --arg branchName "$branchName" 'map(. | select(.branch==$branchName))' json-matrix.json)
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
  show-matrix:
    needs: matrix_prep
    runs-on: ubuntu-latest
    name: Show matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix_prep.outputs.matrix) }}
    #environment: ${{ matrix.environment }}
    steps:
      - name: Step
        run: |
          echo hello
