name: Test2 Workflow
run-name: run-name

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: bg
        shell: bash {0}
        run: |
          bg
          sleep 10 &
          bg
      - name: ps
        run: ps
      - name: lsof
        run: which lsof
      - name: background exec
        run: |
          false &
          echo "after false"
      - name: run bash without -e option
        shell: bash {0}
        run: |
          false
          echo "after false"
      - name: sucess
        run: echo "sucess"
