name: Test2 Workflow
run-name: run-name

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Shell
        continue-on-error: true
        run: |
          which false
          echo "after false"
          false; true;
      - name: sucess
        run: echo "sucess"
