name: Test Workflow
run-name: run-name

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Shell
        run: |
          echo $SHELL
          $SHELL --version
      - name: check
        run: |
          code=42
          if [[ $code -ne 21 ]]; then
            echo "status code: $code"
            exit 1
          fi
      - name: Step1
        run: | 
          node --version
          echo ${{ github }}
          pwd
          cat $GITHUB_ENV
          cat /sys/devices/system/cpu/smt/control 

      - name: Step2
        run: | 
          echo $HOME

      - name: Step3
        run: | 
          sleep 10000 &

      - name: Step4
        run: | 
          tail -f /dev/null &
          ps

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        run: | 
          echo $GITHUB_WORKSPACE
          pwd

      - name: Step2
        run: | 
          echo $HOME

      - name: Step3
        run: | 
          sleep 10000 &

      - name: Step4
        run: | 
          tail -f /dev/null &
          ps
  cpu-info:
    runs-on: ubuntu-latest

    steps:
      - name: CPU Info
        run: | 
          lscpu
