name: Test2 Workflow
run-name: run-name

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: run bash without -e option
        shell: bash {0}
        run: |
          false
          echo "after false"
      - name: sucess
        run: echo "sucess"
