name: Test Workflow
run-name: run-name

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        run: | 
          echo $GITHUB_WORKSPACE
          pwd

      - name: Step2
        run: | 
          echo $HOME

      - name: Step3
        run: | 
          sleep 10000 &

      - name: Step4
        run: | 
          tail -f /dev/null &
          ps

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        run: | 
          echo $GITHUB_WORKSPACE
          pwd

      - name: Step2
        run: | 
          echo $HOME

      - name: Step3
        run: | 
          sleep 10000 &

      - name: Step4
        run: | 
          tail -f /dev/null &
          ps
