name: Usage Report
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  get-actions-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_actions_billing_for_user
        with:
          route: GET /users/{username}/settings/billing/actions
          username: hayashi-ay
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - run: "echo latest release: '${{ steps.get_actions_billing_for_user.outputs.data }}'"

  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.PAT }}
          title: 'test'
          body: 'test'
